class Constants {
  static const List<String> brandName = [
    'Adidas',
    'Converse',
    'Crocs',
    'Nike',
    'Puma',
    'Reebook',
    'Skechers',
    'Reebook',
    'Skechers',
    'Skechers',
    'Reebook',
    'Skechers',
    'Reebook',
    'Skechers',
    'Skechers',
  ];
  static const List<String> itemName = [
    'jaj',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
    'Snakers',
  ];
}
